[tool.ruff]
line-length = 120
ignore = ["E203"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "3dgen"
requires-python = ">=3.8"

[project.optional-dependencies]
# Development / testing dependencies
dev = [
    "pytest",
]

